---
number_of_snps_to_read: 1000
muvr:
  nCore: 2                  # Number of processor threads to use
  nRep: 5                   # Number of MUVR repetitions (whole dataset, whole process)
  nOuter: 8                 # Number of outer cross-validation segments
  nInner: 4                 # number of inner cross-validation segments
  varRatio: 0.8             # Proportion of variables kept per iteration (recursive variable elimination) 
  nPerm: 10                 # Number of permutations (here set to 25 for illustration; normally set to ≥100) 
